/* eslint-disable @next/next/no-img-element */
import Head from "next/head"
import { Courgette } from 'next/font/google'
import { useRouter } from "next/router"
import { NextPageContext } from "next"
import { CompositeDishData } from "@/components/types"
import parse from 'html-react-parser'

const courgette = Courgette({
    weight: ["400", "400"],
    subsets: ["latin"],
    variable: "--font-courgette"
})  

export async function getServerSideProps(context: NextPageContext) {
    const { id } = context.query
    const res = await fetch(`http://localhost:3000/api/dish/${id}`)
    const data = await res.json()
  
    if(data.status === 'ok'){
      let temp = data.payload
      return { props: { data: temp } }
    }
  }
  


export default function DishEx(props: any){
    
    const info: CompositeDishData = props.data
    const link = info.dishpicture
    const procedure = info.procedure
    console.log(procedure)
    
    const render = () => {
        const element = parse(procedure)
        return element
    }

    return(
        <>
            <Head>
                <title>{info.dishname}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="h-screen lg:h-full md:h-screen sm:h-screen w-full flex flex-col bg-slate-800">
                <section className="h-96 w-4/5 lg:w-3/5 mx-auto flex flex-row relative">
                    <section className="lg:basis-1/4 lg:blur-md hidden lg:inline bg-fixed" style={{backgroundImage: `url(${link})`}}></section>
                    <section className="lg:basis-1/2 h-full w-full lg:w-0 flex items-center relative">
                        <img className="w-full h-full" src={link} alt="photo"/>
                        <div className="w-full h-full bg-gradient-to-tr from-black to-blue-400 opacity-40 absolute  "></div>
                        <h4 className={`text-5xl text-white absolute z-10 left-5 top-10 ${courgette.className}`}>{info.dishname}</h4>
                        
                    </section>
                    <section className="lg:basis-1/4 lg:blur-md hidden lg:inline bg-fixed" style={{backgroundImage: `url(${link})`}}></section>
                </section>
                <section className="h-screen w-4/5 lg:w-3/5 mx-auto bg-white text-black">
                    <div className="h-full mx-5">
                        <iframe srcDoc={procedure} className="w-full h-full"></iframe>
                    </div>
                </section>
            </main>
        </>
    )
}